// <auto-generated />
using System;
using InfraBitacoraVehicular.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfraBitacoraVehicular.Migrations
{
    [DbContext(typeof(BitacoraVehicularDbContext))]
    [Migration("20260408140001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.AsignacionVehiculo", b =>
                {
                    b.Property<int>("AsignacionVehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsignacionVehiculoId"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTermino")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("AsignacionVehiculoId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("AsignacionesVehiculo", (string)null);
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.CargaCombustible", b =>
                {
                    b.Property<int>("CargaCombustibleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargaCombustibleId"));

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Litros")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MontoCargado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("NombreArchivoBoleta")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RutaArchivoBoleta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TipoCombustibleId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.Property<int>("ViajeId")
                        .HasColumnType("int");

                    b.HasKey("CargaCombustibleId");

                    b.HasIndex("TipoCombustibleId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VehiculoId");

                    b.HasIndex("ViajeId");

                    b.ToTable("CargasCombustible", (string)null);
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.ContextoEstado", b =>
                {
                    b.Property<int>("ContextoEstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContextoEstadoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ContextoEstadoId");

                    b.ToTable("ContextosEstado", (string)null);
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Estado", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("ContextoEstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EstadoId");

                    b.HasIndex("ContextoEstadoId");

                    b.ToTable("Estados", (string)null);
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Mantencion", b =>
                {
                    b.Property<int>("MantencionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MantencionId"));

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("KilometrajeVehiculo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProximaMantencionFecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProximaMantencionKm")
                        .HasColumnType("int");

                    b.Property<int>("TipoMantencionId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("MantencionId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("TipoMantencionId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Mantenciones", (string)null);
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MarcaId");

                    b.ToTable("Marcas", (string)null);
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Modelo", b =>
                {
                    b.Property<int>("ModeloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModeloId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ModeloId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Modelos", (string)null);
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RolId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.TipoCombustible", b =>
                {
                    b.Property<int>("TipoCombustibleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoCombustibleId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoCombustibleId");

                    b.ToTable("TiposCombustible", (string)null);
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.TipoMantencion", b =>
                {
                    b.Property<int>("TipoMantencionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMantencionId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoMantencionId");

                    b.ToTable("TiposMantencion", (string)null);
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("EstadoId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehiculoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("KilometrajeActual")
                        .HasColumnType("int");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VehiculoId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("ModeloId");

                    b.HasIndex("Patente")
                        .IsUnique();

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Viaje", b =>
                {
                    b.Property<int>("ViajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViajeId"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraLlegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KilometrajeLlegada")
                        .HasColumnType("int");

                    b.Property<int>("KilometrajeSalida")
                        .HasColumnType("int");

                    b.Property<string>("ObservacionLlegada")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ObservacionSalida")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("ViajeId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("UX_Viajes_Usuario_Abierto")
                        .HasFilter("[FechaHoraLlegada] IS NULL");

                    b.HasIndex("VehiculoId")
                        .IsUnique()
                        .HasDatabaseName("UX_Viajes_Vehiculo_Abierto")
                        .HasFilter("[FechaHoraLlegada] IS NULL");

                    b.ToTable("Viajes", (string)null);
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.AsignacionVehiculo", b =>
                {
                    b.HasOne("DomainBitacoraVehicular.Entities.Estado", "Estado")
                        .WithMany("AsignacionesVehiculo")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainBitacoraVehicular.Entities.Usuario", "Usuario")
                        .WithMany("AsignacionesVehiculo")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainBitacoraVehicular.Entities.Vehiculo", "Vehiculo")
                        .WithMany("AsignacionesVehiculo")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.CargaCombustible", b =>
                {
                    b.HasOne("DomainBitacoraVehicular.Entities.TipoCombustible", "TipoCombustible")
                        .WithMany("CargasCombustible")
                        .HasForeignKey("TipoCombustibleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainBitacoraVehicular.Entities.Usuario", "Usuario")
                        .WithMany("CargasCombustible")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainBitacoraVehicular.Entities.Vehiculo", "Vehiculo")
                        .WithMany("CargasCombustible")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainBitacoraVehicular.Entities.Viaje", "Viaje")
                        .WithMany("CargasCombustible")
                        .HasForeignKey("ViajeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoCombustible");

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Estado", b =>
                {
                    b.HasOne("DomainBitacoraVehicular.Entities.ContextoEstado", "ContextoEstado")
                        .WithMany("Estados")
                        .HasForeignKey("ContextoEstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContextoEstado");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Mantencion", b =>
                {
                    b.HasOne("DomainBitacoraVehicular.Entities.Estado", "Estado")
                        .WithMany("Mantenciones")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainBitacoraVehicular.Entities.TipoMantencion", "TipoMantencion")
                        .WithMany("Mantenciones")
                        .HasForeignKey("TipoMantencionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainBitacoraVehicular.Entities.Vehiculo", "Vehiculo")
                        .WithMany("Mantenciones")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("TipoMantencion");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Modelo", b =>
                {
                    b.HasOne("DomainBitacoraVehicular.Entities.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Usuario", b =>
                {
                    b.HasOne("DomainBitacoraVehicular.Entities.Estado", "Estado")
                        .WithMany("Usuarios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainBitacoraVehicular.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Vehiculo", b =>
                {
                    b.HasOne("DomainBitacoraVehicular.Entities.Estado", "Estado")
                        .WithMany("Vehiculos")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainBitacoraVehicular.Entities.Modelo", "Modelo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Viaje", b =>
                {
                    b.HasOne("DomainBitacoraVehicular.Entities.Estado", "Estado")
                        .WithMany("Viajes")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainBitacoraVehicular.Entities.Usuario", "Usuario")
                        .WithMany("Viajes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DomainBitacoraVehicular.Entities.Vehiculo", "Vehiculo")
                        .WithMany("Viajes")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.ContextoEstado", b =>
                {
                    b.Navigation("Estados");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Estado", b =>
                {
                    b.Navigation("AsignacionesVehiculo");

                    b.Navigation("Mantenciones");

                    b.Navigation("Usuarios");

                    b.Navigation("Vehiculos");

                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Modelo", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.TipoCombustible", b =>
                {
                    b.Navigation("CargasCombustible");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.TipoMantencion", b =>
                {
                    b.Navigation("Mantenciones");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Usuario", b =>
                {
                    b.Navigation("AsignacionesVehiculo");

                    b.Navigation("CargasCombustible");

                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Vehiculo", b =>
                {
                    b.Navigation("AsignacionesVehiculo");

                    b.Navigation("CargasCombustible");

                    b.Navigation("Mantenciones");

                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("DomainBitacoraVehicular.Entities.Viaje", b =>
                {
                    b.Navigation("CargasCombustible");
                });
#pragma warning restore 612, 618
        }
    }
}
